version: '3'
services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    networks:
      - kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    networks:
      - kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafdrop:
    container_name: kafdrop
    image: obsidiandynamics/kafdrop:latest
    networks:
      - kafka
    depends_on:
      - kafka
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092


  api-producer:
    container_name: api-producer
    image: openjdk:17-jdk
    restart: unless-stopped
    volumes:
      - ./api-pub/target/demo-1.jar:/app/app.jar
    command: ["java", "-jar", "/app/app.jar"]
    networks:
      - kafka
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - 8080:8080

  api-consumer:
    container_name: api-consumer
    image: openjdk:17-jdk
    restart: unless-stopped
    volumes:
      - ./api-sub/target/demo-1.jar:/app/app.jar
    command: ["java", "-jar", "/app/app.jar"]
    networks:
      - kafka
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - 8082:8082

networks:
  kafka:
    external: true